### ISSUE TITLE
.env example?

### ISSUE THREAD

**Issue by MikeBinstock** [aviflombaum/activestorage-s3-direct-uploader#1]
Could you please include a .env-example to see which variables are required?
Thanks!

**Comment by aviflombaum** [comment]
Closed by [d135cf2](https://github.com/aviflombaum/activestorage-s3-direct-uploader/commit/d135cf2631438371d42714f8a34b5d757821856d)

**Comment by aviflombaum** [comment]
You can also see them in use in config/storage.yml
